version: '3.6'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - 5434:5432
    networks: 
      - default

networks:
  default:
    driver: bridge