version: '3.4'

services:
  timesheets.api:
    image: ${DOCKER_REGISTRY-}timesheetsapi
    build:
      context: .
      dockerfile: Timesheets.API/Dockerfile

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: pwd
    ports:
      - 5434:5432