version: '3.4'

services:
  timesheets.api:
    image: ${DOCKER_REGISTRY-}timesheetsapi
    build:
      context: .
      dockerfile: Timesheets.API/Dockerfile

  db:
    container_name: db
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
    ports:
      - 5434:5432

  seq:
    container_name: seq
    restart: unless-stopped
    image: datalust/seq:latest
    volumes:
    - /seq-data:/data
    ports:
      - 15341:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y

volumes: 
  db-data:
   driver: local