version: '3.4'

services:
  timesheets.api:
    image: ${DOCKER_REGISTRY-}timesheetsapi
    build:
      context: .
      dockerfile: Timesheets.API/Dockerfile

  db:
    container_name: db
    image: postgres
    volumes:
    - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=pwd
    ports:
      - 5434:5432

  seq:
    container_name: seq
    restart: unless-stopped
    image: datalust/seq:latest
    volumes:
    - /seq-data:/data
    ports:
      - 15341:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.34
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411

volumes: 
  db-data:
   driver: local